services:
  - type: web
    name: coreconnect-api
    env: node
    buildCommand: cd server && npm install && npx prisma generate && npm run build && cd ../client && npm install && npm run build
    startCommand: cd server && npx prisma db push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: JWT_ACCESS_EXPIRY
        value: 1h
