import { PrismaClient, UserRole } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

function s(text: string) {
  return text.toLowerCase().replace(/[^\w\s-]/g, '').replace(/[\s_]+/g, '-').replace(/-+/g, '-').trim();
}

async function main() {
  console.log('Seeding CoreConnect database...');

  const hashFor = (password: string) => bcrypt.hash(password, 12);

  const [adminHash, managerHash, employeeHash, anneHash, beckerHash, christineHash, jenniferHash, davidHash, emilyHash, michaelHash, sophiaHash, jamesHash, oliviaHash, danielHash, graceHash, henryHash, isabellaHash, lucasHash, victoriaHash, ethanHash, avaHash, noahHash, miaHash, jackHash, lilyHash, oliverHash] = await Promise.all([
    hashFor('admin123'),
    hashFor('manager123'),
    hashFor('employee123'),
    hashFor('anne123'),
    hashFor('becker123'),
    hashFor('christine123'),
    hashFor('jennifer123'),
    hashFor('david123'),
    hashFor('emily123'),
    hashFor('michael123'),
    hashFor('sophia123'),
    hashFor('james123'),
    hashFor('olivia123'),
    hashFor('daniel123'),
    hashFor('grace123'),
    hashFor('henry123'),
    hashFor('isabella123'),
    hashFor('lucas123'),
    hashFor('victoria123'),
    hashFor('ethan123'),
    hashFor('ava123'),
    hashFor('noah123'),
    hashFor('mia123'),
    hashFor('jack123'),
    hashFor('lily123'),
    hashFor('oliver123'),
  ]);

  await Promise.all([
    prisma.user.upsert({ where: { email: 'admin@coreconnect.com' }, update: {}, create: { email: 'admin@coreconnect.com', passwordHash: adminHash, firstName: 'Admin', lastName: 'User', role: UserRole.ADMIN } }),
    prisma.user.upsert({ where: { email: 'manager@coreconnect.com' }, update: {}, create: { email: 'manager@coreconnect.com', passwordHash: managerHash, firstName: 'Jane', lastName: 'Smith', role: UserRole.MANAGER } }),
    prisma.user.upsert({ where: { email: 'employee1@coreconnect.com' }, update: {}, create: { email: 'employee1@coreconnect.com', passwordHash: employeeHash, firstName: 'Emma', lastName: 'Brown', role: UserRole.EMPLOYEE } }),
    prisma.user.upsert({ where: { email: 'employee2@coreconnect.com' }, update: {}, create: { email: 'employee2@coreconnect.com', passwordHash: employeeHash, firstName: 'Liam', lastName: 'Wilson', role: UserRole.EMPLOYEE } }),
    prisma.user.upsert({ where: { email: 'anne@coreconnect.com' }, update: {}, create: { email: 'anne@coreconnect.com', passwordHash: anneHash, firstName: 'Anne', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'becker@coreconnect.com' }, update: {}, create: { email: 'becker@coreconnect.com', passwordHash: beckerHash, firstName: 'Becker', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'christine@coreconnect.com' }, update: {}, create: { email: 'christine@coreconnect.com', passwordHash: christineHash, firstName: 'Christine', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'jennifer@coreconnect.com' }, update: {}, create: { email: 'jennifer@coreconnect.com', passwordHash: jenniferHash, firstName: 'Jennifer', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'david@coreconnect.com' }, update: {}, create: { email: 'david@coreconnect.com', passwordHash: davidHash, firstName: 'David', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'emily@coreconnect.com' }, update: {}, create: { email: 'emily@coreconnect.com', passwordHash: emilyHash, firstName: 'Emily', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'michael@coreconnect.com' }, update: {}, create: { email: 'michael@coreconnect.com', passwordHash: michaelHash, firstName: 'Michael', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'sophia@coreconnect.com' }, update: {}, create: { email: 'sophia@coreconnect.com', passwordHash: sophiaHash, firstName: 'Sophia', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'james@coreconnect.com' }, update: {}, create: { email: 'james@coreconnect.com', passwordHash: jamesHash, firstName: 'James', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'olivia@coreconnect.com' }, update: {}, create: { email: 'olivia@coreconnect.com', passwordHash: oliviaHash, firstName: 'Olivia', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'daniel@coreconnect.com' }, update: {}, create: { email: 'daniel@coreconnect.com', passwordHash: danielHash, firstName: 'Daniel', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'grace@coreconnect.com' }, update: {}, create: { email: 'grace@coreconnect.com', passwordHash: graceHash, firstName: 'Grace', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'henry@coreconnect.com' }, update: {}, create: { email: 'henry@coreconnect.com', passwordHash: henryHash, firstName: 'Henry', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'isabella@coreconnect.com' }, update: {}, create: { email: 'isabella@coreconnect.com', passwordHash: isabellaHash, firstName: 'Isabella', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'lucas@coreconnect.com' }, update: {}, create: { email: 'lucas@coreconnect.com', passwordHash: lucasHash, firstName: 'Lucas', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'victoria@coreconnect.com' }, update: {}, create: { email: 'victoria@coreconnect.com', passwordHash: victoriaHash, firstName: 'Victoria', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'ethan@coreconnect.com' }, update: {}, create: { email: 'ethan@coreconnect.com', passwordHash: ethanHash, firstName: 'Ethan', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'ava@coreconnect.com' }, update: {}, create: { email: 'ava@coreconnect.com', passwordHash: avaHash, firstName: 'Ava', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'noah@coreconnect.com' }, update: {}, create: { email: 'noah@coreconnect.com', passwordHash: noahHash, firstName: 'Noah', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'mia@coreconnect.com' }, update: {}, create: { email: 'mia@coreconnect.com', passwordHash: miaHash, firstName: 'Mia', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'jack@coreconnect.com' }, update: {}, create: { email: 'jack@coreconnect.com', passwordHash: jackHash, firstName: 'Jack', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'lily@coreconnect.com' }, update: {}, create: { email: 'lily@coreconnect.com', passwordHash: lilyHash, firstName: 'Lily', lastName: '', role: UserRole.CUSTOMER } }),
    prisma.user.upsert({ where: { email: 'oliver@coreconnect.com' }, update: {}, create: { email: 'oliver@coreconnect.com', passwordHash: oliverHash, firstName: 'Oliver', lastName: '', role: UserRole.CUSTOMER } }),
  ]);

  const categoriesData = [
    { name: 'Computer Components', slug: 'computer-components', description: 'CPUs, GPUs, motherboards, RAM, storage, PSUs, coolers, cases' },
    { name: 'Peripherals', slug: 'peripherals', description: 'Keyboards, mice, monitors, headsets, speakers' },
    { name: 'Mobile Accessories', slug: 'mobile-accessories', description: 'Chargers, cables, power banks, cases, screen protectors' },
    { name: 'Audio', slug: 'audio', description: 'Earbuds, headphones, Bluetooth speakers, sound systems' },
    { name: 'Storage', slug: 'storage', description: 'USB drives, memory cards, external HDDs and SSDs, NAS' },
    { name: 'Networking', slug: 'networking', description: 'Routers, mesh Wi-Fi, switches, cables, adapters' },
    { name: 'Security & Surveillance', slug: 'security-surveillance', description: 'CCTV cameras, doorbells, locks, alarm systems' },
    { name: 'Cameras & Photography', slug: 'cameras-photography', description: 'DSLR, mirrorless, action cams, accessories' },
    { name: 'Gaming', slug: 'gaming', description: 'Gaming mice, keyboards, headsets, chairs, controllers' },
    { name: 'Smart Home', slug: 'smart-home', description: 'Smart bulbs, plugs, switches, sensors' },
    { name: 'Laptop Accessories', slug: 'laptop-accessories', description: 'Bags, cooling pads, USB hubs, docking stations' },
    { name: 'Office Electronics', slug: 'office-electronics', description: 'Printers, scanners, projectors, UPS' },
    { name: 'Cables & Adapters', slug: 'cables-adapters', description: 'HDMI, USB-C, Lightning, Ethernet cables and hubs' },
    { name: 'Power Solutions', slug: 'power-solutions', description: 'UPS, surge protectors, charging stations' },
    { name: 'Wearables', slug: 'wearables', description: 'Smart watches, fitness bands, VR headsets' },
    { name: 'Software & Digital', slug: 'software-digital', description: 'Windows licenses, Office, antivirus, gift cards' },
    { name: 'DIY Electronics', slug: 'diy-electronics', description: 'Arduino, Raspberry Pi, sensors, components' },
    { name: 'Tools & Maintenance', slug: 'tools-maintenance', description: 'Screwdriver sets, cleaning kits, toolkits' },
  ];

  for (const cat of categoriesData) {
    await prisma.category.upsert({ where: { slug: cat.slug }, update: {}, create: cat });
  }
  const cats = await prisma.category.findMany();
  const getCat = (slug: string) => cats.find(c => c.slug === slug)!;

  const brandsData = [
    'Intel', 'AMD', 'NVIDIA', 'ASUS', 'MSI', 'Gigabyte', 'Corsair', 'Kingston', 'Crucial', 'WD', 'Seagate',
    'Samsung', 'Logitech', 'Razer', 'Keychron', 'HyperX', 'SteelSeries',
    'Anker', 'UGREEN', 'Baseus', 'Xiaomi', 'Spigen', 'Belkin', 'Apple',
    'Sony', 'JBL', 'Bose', 'NZXT', 'Noctua', 'DeepCool', 'Lian Li', 'EVGA', 'Thermal Grizzly',
    'SanDisk', 'Synology', 'QNAP', 'TP-Link', 'Netgear', 'Ubiquiti',
    'Hikvision', 'Dahua', 'Reolink', 'Ring', 'Google',
    'Canon', 'Nikon', 'Fujifilm', 'GoPro', 'DJI',
    'Secretlab', 'Herman Miller', 'Microsoft', 'Elgato', 'Philips',
    'Peak Design', 'Rain Design', 'Brother', 'Epson', 'BenQ', 'Tripp Lite', 'APC',
    'Garmin', 'Meta', 'Norton', 'Arduino', 'Raspberry Pi', 'ELEGOO',
    'iFixit', 'ORIA',
  ];

  for (const name of brandsData) {
    const slug = s(name);
    await prisma.brand.upsert({ where: { slug }, update: {}, create: { name, slug } });
  }
  const brands = await prisma.brand.findMany();
  const getBrand = (name: string) => brands.find(b => b.name === name);

  interface PData {
    name: string; category: string; brand: string; price: number; stock: number; sku: string;
    description: string; shortDesc: string; tags: string[]; specs: Record<string, string>;
    comparePrice?: number; isFeatured?: boolean; isDigital?: boolean;
  }

  const products: PData[] = [
    // ===== 1. COMPUTER COMPONENTS =====
    { name: 'Intel Core i9-14900K', category: 'computer-components', brand: 'Intel', price: 589.99, stock: 45, sku: 'CC-CPU-INT-001', description: '24 cores (8P+16E), up to 6.0 GHz, 36MB cache, DDR5-5600, PCIe 5.0, LGA 1700. Unlocked for overclocking. The definitive enthusiast processor for gaming and creation.', shortDesc: '24 cores, 6.0 GHz, 36MB cache, unlocked', tags: ['cpu', 'intel', 'i9', '14th-gen'], specs: { cores: '24 (8P+16E)', 'max clock': '6.0 GHz', cache: '36MB', socket: 'LGA 1700', tdp: '125W' }, isFeatured: true },
    { name: 'AMD Ryzen 9 7950X3D', category: 'computer-components', brand: 'AMD', price: 549.99, stock: 32, sku: 'CC-CPU-AMD-001', description: '16 cores, 3D V-Cache technology, 128MB total cache, up to 5.7 GHz, AM5 socket. Up to 15% faster gaming than standard 7950X. 120W TDP.', shortDesc: '16 cores, 3D V-Cache, 128MB cache, 5.7 GHz', tags: ['cpu', 'amd', 'ryzen-9', '3d-vcache'], specs: { cores: '16', 'max clock': '5.7 GHz', cache: '128MB', socket: 'AM5', tdp: '120W' }, isFeatured: true },
    { name: 'Intel Core i5-14600K', category: 'computer-components', brand: 'Intel', price: 319.99, stock: 78, sku: 'CC-CPU-INT-002', description: '14 cores (6P+8E), up to 5.3 GHz, 24MB cache. The sweet spot for 1440p gaming builds without breaking the bank.', shortDesc: '14 cores, 5.3 GHz, 24MB cache', tags: ['cpu', 'intel', 'i5', '14th-gen'], specs: { cores: '14 (6P+8E)', 'max clock': '5.3 GHz', cache: '24MB', socket: 'LGA 1700', tdp: '125W' } },
    { name: 'NVIDIA GeForce RTX 4090 Founders Edition', category: 'computer-components', brand: 'NVIDIA', price: 1599.99, stock: 12, sku: 'CC-GPU-NVD-001', description: '24GB GDDR6X, 16,384 CUDA cores, DLSS 3, 3rd-gen RT Cores. The most powerful consumer GPU ever. Dual-axial flow-through design.', shortDesc: '24GB GDDR6X, 16,384 CUDA cores, DLSS 3', tags: ['gpu', 'nvidia', 'rtx-4090', '4k-gaming'], specs: { memory: '24GB GDDR6X', 'cuda cores': '16384', dlss: '3.0', interface: 'PCIe 4.0 x16' }, isFeatured: true, comparePrice: 1699.99 },
    { name: 'ASUS ROG Strix RTX 4080 OC', category: 'computer-components', brand: 'ASUS', price: 1199.99, stock: 23, sku: 'CC-GPU-ASU-001', description: '16GB GDDR6X, factory OC to 2625 MHz, 3.5-slot vapor chamber cooling, AURA Sync RGB. Axial-tech fans push 31% more air.', shortDesc: '16GB GDDR6X, 2625 MHz OC, vapor chamber', tags: ['gpu', 'asus', 'rtx-4080', 'gaming'], specs: { memory: '16GB GDDR6X', 'boost clock': '2625 MHz', cooling: '3.5-slot vapor chamber', interface: 'PCIe 4.0' } },
    { name: 'MSI Gaming X Trio RTX 4070 Ti', category: 'computer-components', brand: 'MSI', price: 799.99, stock: 34, sku: 'CC-GPU-MSI-001', description: '12GB GDDR6X, TRI FROZR 3 cooling, Torx Fan 5.0. Perfect for 1440p high-refresh gaming.', shortDesc: '12GB GDDR6X, TRI FROZR 3, 1440p gaming', tags: ['gpu', 'msi', 'rtx-4070-ti'], specs: { memory: '12GB GDDR6X', cooling: 'TRI FROZR 3', interface: 'PCIe 4.0' } },
    { name: 'ASUS ROG Maximus Z790 Hero', category: 'computer-components', brand: 'ASUS', price: 629.99, stock: 18, sku: 'CC-MBD-ASU-001', description: '20+1 90A power stages, DDR5-7800+, 5x M.2 slots (1x PCIe 5.0), Thunderbolt 4, Wi-Fi 6E. Polymo Lighting display.', shortDesc: 'Z790, 20+1 power stages, DDR5-7800+, Wi-Fi 6E', tags: ['motherboard', 'asus', 'z790', 'ddr5'], specs: { socket: 'LGA 1700', chipset: 'Z790', memory: 'DDR5-7800+', 'm2 slots': '5', wifi: 'Wi-Fi 6E' } },
    { name: 'MSI MPG Z790 Carbon WiFi', category: 'computer-components', brand: 'MSI', price: 479.99, stock: 29, sku: 'CC-MBD-MSI-002', description: '19+1+1 power design, DDR5-7600, 4x M.2, carbon fiber aesthetics. Extended heatsink for sustained loads.', shortDesc: 'Z790, 19+1+1 VRM, DDR5-7600, carbon fiber', tags: ['motherboard', 'msi', 'z790', 'ddr5'], specs: { socket: 'LGA 1700', chipset: 'Z790', memory: 'DDR5-7600', 'm2 slots': '4' } },
    { name: 'Gigabyte Z790 AORUS Elite AX', category: 'computer-components', brand: 'Gigabyte', price: 259.99, stock: 45, sku: 'CC-MBD-GIG-001', description: '16+1+2 VRM, DDR5-7600, 2.5GbE LAN, Wi-Fi 6E. Best value Z790 board with Q-Flash Plus.', shortDesc: 'Z790, 16+1+2 VRM, DDR5-7600, Wi-Fi 6E', tags: ['motherboard', 'gigabyte', 'z790', 'ddr5'], specs: { socket: 'LGA 1700', chipset: 'Z790', memory: 'DDR5-7600', lan: '2.5GbE' } },
    { name: 'Corsair Vengeance RGB 32GB DDR5 6000MHz', category: 'computer-components', brand: 'Corsair', price: 129.99, stock: 120, sku: 'CC-RAM-CRR-001', description: 'CL36, XMP 3.0 / EXPO, 10 RGB LEDs per module, iCUE software. Aluminum heat spreader. 2x16GB kit.', shortDesc: '32GB (2x16GB) DDR5 6000MHz, CL36, RGB', tags: ['ram', 'ddr5', '32gb', 'rgb'], specs: { capacity: '32GB (2x16GB)', speed: '6000MHz', latency: 'CL36', type: 'DDR5' } },
    { name: 'Kingston Fury Beast 32GB DDR5 5600MHz', category: 'computer-components', brand: 'Kingston', price: 99.99, stock: 156, sku: 'CC-RAM-KIN-001', description: 'Plug-and-play 5600MHz, Intel XMP 3.0 certified. Low-profile design. Lifetime warranty. 2x16GB kit.', shortDesc: '32GB (2x16GB) DDR5 5600MHz, plug-and-play', tags: ['ram', 'ddr5', '32gb', 'kingston'], specs: { capacity: '32GB (2x16GB)', speed: '5600MHz', type: 'DDR5', warranty: 'Lifetime' } },
    { name: 'Crucial Pro 64GB DDR5 5600MHz', category: 'computer-components', brand: 'Crucial', price: 189.99, stock: 67, sku: 'CC-RAM-CRU-001', description: 'Professional-grade for creators. Micron quality chips. No RGB, pure performance. 2x32GB kit.', shortDesc: '64GB (2x32GB) DDR5 5600MHz, professional', tags: ['ram', 'ddr5', '64gb', 'crucial'], specs: { capacity: '64GB (2x32GB)', speed: '5600MHz', type: 'DDR5' } },
    { name: 'Samsung 990 Pro 2TB NVMe SSD', category: 'computer-components', brand: 'Samsung', price: 169.99, stock: 89, sku: 'CC-SSD-SAM-001', description: 'Up to 7,450 MB/s read, 6,900 MB/s write. V-NAND 7th Gen, 1,400K IOPS. 1,200TBW endurance. PS5 compatible.', shortDesc: '2TB NVMe, 7,450 MB/s read, PCIe 4.0', tags: ['ssd', 'nvme', '2tb', 'samsung'], specs: { capacity: '2TB', read: '7450 MB/s', write: '6900 MB/s', interface: 'PCIe 4.0 NVMe M.2', endurance: '1200TBW' }, isFeatured: true, comparePrice: 229.99 },
    { name: 'WD Black SN850X 2TB NVMe SSD', category: 'computer-components', brand: 'WD', price: 149.99, stock: 112, sku: 'CC-SSD-WD-001', description: 'Up to 7,300 MB/s reads, Game Mode 2.0, predictive loading. RGB heatsink option available.', shortDesc: '2TB NVMe, 7,300 MB/s, Game Mode 2.0', tags: ['ssd', 'nvme', '2tb', 'wd'], specs: { capacity: '2TB', read: '7300 MB/s', interface: 'PCIe 4.0 NVMe M.2' } },
    { name: 'Crucial T500 2TB NVMe SSD', category: 'computer-components', brand: 'Crucial', price: 139.99, stock: 94, sku: 'CC-SSD-CRU-002', description: 'Up to 7,400 MB/s reads, 232-layer TLC NAND, DirectStorage optimized.', shortDesc: '2TB NVMe, 7,400 MB/s, DirectStorage', tags: ['ssd', 'nvme', '2tb', 'crucial'], specs: { capacity: '2TB', read: '7400 MB/s', nand: '232-layer TLC', interface: 'PCIe 4.0 NVMe M.2' } },
    { name: 'Seagate Barracuda 4TB HDD', category: 'computer-components', brand: 'Seagate', price: 89.99, stock: 200, sku: 'CC-HDD-SEA-001', description: '5400RPM, 256MB cache, quiet operation. Multi-tier caching. Perfect for media storage and backups.', shortDesc: '4TB 5400RPM HDD, 256MB cache', tags: ['hdd', '4tb', 'seagate', 'storage'], specs: { capacity: '4TB', rpm: '5400', cache: '256MB', interface: 'SATA III' } },
    { name: 'WD Black 8TB 7200RPM HDD', category: 'computer-components', brand: 'WD', price: 229.99, stock: 78, sku: 'CC-HDD-WD-002', description: '7200RPM, 256MB cache, StableTrac vibration protection. 200+ game capacity. Dual-core processor.', shortDesc: '8TB 7200RPM HDD, performance storage', tags: ['hdd', '8tb', 'wd', 'performance'], specs: { capacity: '8TB', rpm: '7200', cache: '256MB', interface: 'SATA III' } },
    { name: 'Corsair RM1000x Shift 1000W PSU', category: 'computer-components', brand: 'Corsair', price: 189.99, stock: 45, sku: 'CC-PSU-CRR-001', description: 'Side-mounted connectors, 80+ Gold, ATX 3.0, native 12VHPWR. Zero RPM fan mode. 10-year warranty.', shortDesc: '1000W, 80+ Gold, ATX 3.0, fully modular', tags: ['psu', '1000w', 'corsair', 'modular'], specs: { wattage: '1000W', rating: '80+ Gold', type: 'Fully Modular', atx: 'ATX 3.0', warranty: '10 years' } },
    { name: 'ASUS ROG Thor 1200W Platinum II', category: 'computer-components', brand: 'ASUS', price: 349.99, stock: 22, sku: 'CC-PSU-ASU-002', description: 'OLED power display, Lambda A++ noise, ROG heatsinks. 80+ Platinum efficiency.', shortDesc: '1200W, 80+ Platinum, OLED display', tags: ['psu', '1200w', 'asus', 'platinum'], specs: { wattage: '1200W', rating: '80+ Platinum', display: 'OLED Power', warranty: '10 years' } },
    { name: 'EVGA SuperNOVA 850 G7 850W', category: 'computer-components', brand: 'EVGA', price: 129.99, stock: 67, sku: 'CC-PSU-EVG-001', description: 'Compact ATX, 140mm HDB fan, ECO mode. Fully modular. 10-year warranty.', shortDesc: '850W, 80+ Gold, fully modular, compact', tags: ['psu', '850w', 'evga', 'gold'], specs: { wattage: '850W', rating: '80+ Gold', type: 'Fully Modular', warranty: '10 years' } },
    { name: 'NZXT Kraken Elite 360 RGB', category: 'computer-components', brand: 'NZXT', price: 289.99, stock: 34, sku: 'CC-CLR-NZX-001', description: '2.36" LCD display, Asetek 8th gen pump, F RGB Core fans. CAM software control. 360mm radiator.', shortDesc: '360mm AIO, LCD display, RGB fans', tags: ['cooler', 'aio', '360mm', 'nzxt', 'lcd'], specs: { type: 'AIO Liquid', radiator: '360mm', display: '2.36" LCD', pump: 'Asetek 8th Gen' } },
    { name: 'Noctua NH-D15 chromax.black', category: 'computer-components', brand: 'Noctua', price: 109.99, stock: 56, sku: 'CC-CLR-NOC-001', description: 'Dual 140mm fans, 6 heatpipes, RAM clearance. Near-silent operation. NT-H1 included. All-black design.', shortDesc: 'Dual tower, 140mm fans, 6 heatpipes, silent', tags: ['cooler', 'air', 'noctua', 'silent'], specs: { type: 'Air Cooler', fans: '2x 140mm', heatpipes: '6', height: '165mm' } },
    { name: 'DeepCool AK620', category: 'computer-components', brand: 'DeepCool', price: 64.99, stock: 89, sku: 'CC-CLR-DPC-001', description: 'Dual-tower, dual 120mm FK120 fans, 6 heatpipes. 157mm height. Exceptional value air cooler.', shortDesc: 'Dual tower, 120mm fans, exceptional value', tags: ['cooler', 'air', 'deepcool', 'budget'], specs: { type: 'Air Cooler', fans: '2x 120mm', heatpipes: '6', height: '157mm' } },
    { name: 'Lian Li O11 Dynamic EVO', category: 'computer-components', brand: 'Lian Li', price: 169.99, stock: 41, sku: 'CC-CSE-LAN-001', description: 'Dual chamber, modular orientation, up to 420mm radiators. Reversible motherboard tray. Tempered glass panels.', shortDesc: 'Dual chamber, modular, tempered glass', tags: ['case', 'lian-li', 'mid-tower', 'tempered-glass'], specs: { type: 'Mid Tower', motherboard: 'ATX/E-ATX', radiators: 'Up to 420mm', chambers: 'Dual' } },
    { name: 'Corsair 4000D Airflow', category: 'computer-components', brand: 'Corsair', price: 94.99, stock: 89, sku: 'CC-CSE-CRR-002', description: 'High-airflow front panel, 360mm radiator support, RapidRoute cable management. Tempered glass side panel.', shortDesc: 'High airflow, 360mm radiator, cable management', tags: ['case', 'corsair', 'mid-tower', 'airflow'], specs: { type: 'Mid Tower', motherboard: 'ATX', radiator: '360mm', side: 'Tempered Glass' } },
    { name: 'NZXT H7 Flow', category: 'computer-components', brand: 'NZXT', price: 129.99, stock: 56, sku: 'CC-CSE-NZX-002', description: 'Perforated front/top, dual 360mm radiator support, improved GPU clearance. Clean minimalist design.', shortDesc: 'Dual 360mm radiator, high GPU clearance', tags: ['case', 'nzxt', 'mid-tower', 'minimal'], specs: { type: 'Mid Tower', motherboard: 'ATX', radiator: 'Dual 360mm', gpu: 'Up to 400mm' } },
    { name: 'Thermal Grizzly Kryonaut 1g', category: 'computer-components', brand: 'Thermal Grizzly', price: 9.99, stock: 300, sku: 'CC-THP-TGR-001', description: '12.5 W/mK conductivity. Non-conductive. Best thermal paste for overclockers. 1 gram syringe.', shortDesc: '12.5 W/mK, non-conductive, 1 gram', tags: ['thermal-paste', 'kryonaut', 'overclocking'], specs: { conductivity: '12.5 W/mK', weight: '1g', type: 'Non-conductive' } },
    { name: 'Noctua NT-H2 3.5g', category: 'computer-components', brand: 'Noctua', price: 12.99, stock: 200, sku: 'CC-THP-NOC-002', description: '11.9 W/mK, includes 3 cleaning wipes. Long-term stability. 10+ applications per syringe.', shortDesc: '11.9 W/mK, 3.5g, cleaning wipes included', tags: ['thermal-paste', 'noctua', 'nt-h2'], specs: { conductivity: '11.9 W/mK', weight: '3.5g', durability: 'Long-term stable' } },

    // ===== 2. PERIPHERALS =====
    { name: 'Logitech G Pro X TKL Keyboard', category: 'peripherals', brand: 'Logitech', price: 149.99, stock: 67, sku: 'CC-KBD-LOG-001', description: 'Tenkeyless, GX Blue Clicky switches, LIGHTSYNC RGB, detachable USB-C. Esports standard tournament keyboard.', shortDesc: 'TKL, GX Blue Clicky, LIGHTSYNC RGB', tags: ['keyboard', 'logitech', 'tkl', 'esports'], specs: { layout: 'Tenkeyless', switches: 'GX Blue Clicky', backlight: 'LIGHTSYNC RGB', connection: 'USB-C Detachable' } },
    { name: 'Razer BlackWidow V4 Pro', category: 'peripherals', brand: 'Razer', price: 229.99, stock: 45, sku: 'CC-KBD-RAZ-001', description: 'Razer Yellow linear switches, command dial, 8 macro keys, Chroma underglow. Full-size mechanical gaming keyboard.', shortDesc: 'Full-size, Yellow linear, command dial', tags: ['keyboard', 'razer', 'mechanical', 'gaming'], specs: { switches: 'Razer Yellow Linear', layout: 'Full-size', macros: '8 keys', backlight: 'Chroma RGB' }, isFeatured: true, comparePrice: 249.99 },
    { name: 'Keychron Q1 Pro', category: 'peripherals', brand: 'Keychron', price: 199.99, stock: 38, sku: 'CC-KBD-KEY-001', description: '75% aluminum wireless, hot-swappable, QMK/VIA programmable, gasket mount. Premium custom keyboard experience.', shortDesc: '75% aluminum, wireless, hot-swap, QMK/VIA', tags: ['keyboard', 'keychron', 'wireless', 'aluminum'], specs: { layout: '75%', material: 'Aluminum', connection: 'Wireless/USB-C', switches: 'Hot-swappable' } },
    { name: 'Logitech G Pro X Superlight 2', category: 'peripherals', brand: 'Logitech', price: 159.99, stock: 73, sku: 'CC-MSE-LOG-001', description: '<60g ultra-lightweight, HERO 2 32K DPI sensor, LIGHTFORCE hybrid switches, 95-hour battery. Pro esports choice.', shortDesc: '<60g, 32K DPI, 95hr battery, wireless', tags: ['mouse', 'logitech', 'wireless', 'esports'], specs: { weight: '60g', sensor: 'HERO 2 32K', battery: '95 hours', switches: 'LIGHTFORCE' }, isFeatured: true },
    { name: 'Razer DeathAdder V3 Pro', category: 'peripherals', brand: 'Razer', price: 149.99, stock: 61, sku: 'CC-MSE-RAZ-002', description: '63g, Focus Pro 30K optical sensor, 90-hour battery, ergonomic right-hand design. Wireless esports mouse.', shortDesc: '63g, 30K DPI, 90hr battery, ergonomic', tags: ['mouse', 'razer', 'wireless', 'ergonomic'], specs: { weight: '63g', sensor: 'Focus Pro 30K', battery: '90 hours', design: 'Ergonomic right-hand' } },
    { name: 'Logitech MX Master 3S', category: 'peripherals', brand: 'Logitech', price: 99.99, stock: 120, sku: 'CC-MSE-LOG-003', description: '8K DPI Anywhere sensor, MagSpeed electromagnetic scroll wheel, quiet clicks, multi-device Flow. Premium productivity mouse.', shortDesc: '8K DPI, MagSpeed wheel, quiet clicks', tags: ['mouse', 'logitech', 'productivity', 'wireless'], specs: { sensor: '8K DPI Anywhere', wheel: 'MagSpeed', battery: '70 days', connectivity: 'Bluetooth + USB' }, isFeatured: true, comparePrice: 119.99 },
    { name: 'ASUS ROG Swift PG27AQDM 27" OLED', category: 'peripherals', brand: 'ASUS', price: 999.99, stock: 15, sku: 'CC-MON-ASU-001', description: '27" 1440p OLED, 240Hz, 0.03ms response, 1000 nits HDR, G-SYNC Compatible. Ultimate esports monitor.', shortDesc: '27" 1440p OLED, 240Hz, 0.03ms', tags: ['monitor', 'asus', 'oled', '240hz', 'gaming'], specs: { size: '27"', resolution: '2560x1440', refresh: '240Hz', panel: 'OLED', hdr: 'HDR10 1000 nits' } },
    { name: 'Samsung Odyssey G9 49"', category: 'peripherals', brand: 'Samsung', price: 1299.99, stock: 9, sku: 'CC-MON-SAM-001', description: '49" DQHD super ultrawide, 1000R curve, 240Hz, Quantum Mini-LED, HDR2000. Immersive gaming and productivity.', shortDesc: '49" DQHD, 1000R curve, 240Hz, Mini-LED', tags: ['monitor', 'samsung', 'ultrawide', '240hz'], specs: { size: '49"', resolution: '5120x1440', curve: '1000R', refresh: '240Hz', panel: 'Quantum Mini-LED' } },
    { name: 'MSI Optix MAG274QRF-QD 27"', category: 'peripherals', brand: 'MSI', price: 399.99, stock: 34, sku: 'CC-MON-MSI-001', description: '27" Quantum Dot IPS, 165Hz, 1ms, G-SYNC Compatible, 95% DCI-P3. Exceptional color accuracy for gaming.', shortDesc: '27" QD-IPS, 165Hz, 1ms, 95% DCI-P3', tags: ['monitor', 'msi', 'ips', '165hz'], specs: { size: '27"', resolution: '2560x1440', refresh: '165Hz', panel: 'Quantum Dot IPS', 'color gamut': '95% DCI-P3' } },
    { name: 'Razer BlackShark V2 Pro Wireless', category: 'peripherals', brand: 'Razer', price: 179.99, stock: 62, sku: 'CC-HST-RAZ-001', description: 'Triforce Titanium 50mm drivers, HyperClear supercardioid mic, 70-hour battery, passive noise cancellation. Wireless esports headset.', shortDesc: '50mm drivers, HyperClear mic, 70hr battery', tags: ['headset', 'razer', 'wireless', 'gaming'], specs: { drivers: 'Triforce Titanium 50mm', mic: 'HyperClear', battery: '70 hours', weight: '320g' } },
    { name: 'HyperX Cloud Alpha Wireless', category: 'peripherals', brand: 'HyperX', price: 199.99, stock: 38, sku: 'CC-HST-HYP-001', description: '300-hour battery life, Dual Chamber Drivers, DTS Headphone:X spatial audio. Record-breaking wireless longevity.', shortDesc: '300hr battery, dual chamber, DTS Headphone:X', tags: ['headset', 'hyperx', 'wireless', '300hr'], specs: { battery: '300 hours', drivers: 'Dual Chamber 50mm', audio: 'DTS Headphone:X', weight: '335g' } },
    { name: 'SteelSeries Arctis Nova Pro Wireless', category: 'peripherals', brand: 'SteelSeries', price: 349.99, stock: 21, sku: 'CC-HST-SSL-002', description: 'Active noise cancellation, Infinity Power System with hot-swap batteries, Sonar Software EQ. Premium wireless audio.', shortDesc: 'ANC, hot-swap batteries, Sonar EQ', tags: ['headset', 'steelseries', 'wireless', 'anc'], specs: { drivers: '40mm High Fidelity', anc: 'Active Noise Cancellation', battery: 'Hot-swap dual', software: 'Sonar EQ' } },
    { name: 'Logitech Z906 5.1 Surround', category: 'peripherals', brand: 'Logitech', price: 349.99, stock: 28, sku: 'CC-SPK-LOG-001', description: 'THX-certified, 500W RMS, Dolby Digital/DTS decoding, console control hub. Room-shaking 5.1 surround sound.', shortDesc: 'THX certified, 500W RMS, 5.1 surround', tags: ['speakers', 'logitech', '5.1', 'thx'], specs: { channels: '5.1', power: '500W RMS', certification: 'THX', inputs: 'Optical, Coaxial, 3.5mm, RCA' } },
    { name: 'JBL Flip 6 Portable', category: 'peripherals', brand: 'JBL', price: 129.99, stock: 89, sku: 'CC-SPK-JBL-001', description: 'IP67 waterproof and dustproof, 12-hour battery, PartyBoost, racetrack driver. Bold JBL Original Pro Sound.', shortDesc: 'IP67 waterproof, 12hr battery, PartyBoost', tags: ['speaker', 'jbl', 'portable', 'waterproof'], specs: { battery: '12 hours', ip: 'IP67', output: '20W', driver: 'Racetrack' }, isFeatured: true, comparePrice: 149.99 },
    { name: 'Bose Companion 2 Series III', category: 'peripherals', brand: 'Bose', price: 149.99, stock: 67, sku: 'CC-SPK-BOS-001', description: 'TrueSpace stereo processing, dual inputs, ported cabinet design. Premium desktop multimedia speakers.', shortDesc: 'TrueSpace stereo, dual inputs, desktop', tags: ['speakers', 'bose', 'desktop', 'stereo'], specs: { channels: '2.0', inputs: 'Dual 3.5mm', technology: 'TrueSpace', type: 'Desktop' } },

    // ===== 3. MOBILE ACCESSORIES =====
    { name: 'Anker 737 Charger 120W GaNPrime', category: 'mobile-accessories', brand: 'Anker', price: 59.99, stock: 200, sku: 'CC-FCH-ANK-001', description: '2C1A ports, ActiveShield 2.0 temperature monitoring, 53% smaller than Apple 96W charger. Intelligent power distribution across ports.', shortDesc: '120W GaN, 2C1A, 53% smaller than Apple', tags: ['charger', 'anker', 'gan', '120w'], specs: { power: '120W', ports: '2x USB-C + 1x USB-A', technology: 'GaNPrime', protection: 'ActiveShield 2.0' } },
    { name: 'Samsung 45W Super Fast Charger', category: 'mobile-accessories', brand: 'Samsung', price: 39.99, stock: 145, sku: 'CC-FCH-SAM-001', description: 'Official Samsung 45W charger. USB-C PD PPS support for Galaxy S24 Ultra super fast charging. Compact, travel-friendly design.', shortDesc: '45W, USB-C PD PPS, official Samsung', tags: ['charger', 'samsung', '45w', 'usb-c'], specs: { power: '45W', port: 'USB-C', protocol: 'PD PPS', compatibility: 'Galaxy S24 Ultra' } },
    { name: 'Apple 30W USB-C Power Adapter', category: 'mobile-accessories', brand: 'Apple', price: 39.00, stock: 200, sku: 'CC-FCH-APL-002', description: 'Official Apple 30W USB-C power adapter. Fast-charges iPhone 15 Pro to 50% in 30 minutes. Foldable prongs for portability.', shortDesc: '30W USB-C, fast charges iPhone to 50% in 30min', tags: ['charger', 'apple', '30w', 'usb-c'], specs: { power: '30W', port: 'USB-C', fastCharge: '50% in 30 min', design: 'Foldable prongs' } },
    { name: 'Anker 737 Power Bank 24K', category: 'mobile-accessories', brand: 'Anker', price: 109.99, stock: 89, sku: 'CC-PWB-ANK-001', description: '24,000mAh capacity, 140W bidirectional output, smart TFT display, 52-minute self-recharge. Airline-compliant.', shortDesc: '24,000mAh, 140W output, smart display', tags: ['power-bank', 'anker', '24000mah', '140w'], specs: { capacity: '24000mAh', output: '140W', display: 'Smart TFT', 'self-charge': '52 min' }, isFeatured: true, comparePrice: 129.99 },
    { name: 'Xiaomi 20000mAh 50W Power Bank', category: 'mobile-accessories', brand: 'Xiaomi', price: 39.99, stock: 156, sku: 'CC-PWB-XIA-001', description: '50W fast charging, aluminum body, LED battery indicator. Charges Mi 13 Pro in 45 minutes. Slim and portable.', shortDesc: '20000mAh, 50W, aluminum, LED indicator', tags: ['power-bank', 'xiaomi', '20000mah', '50w'], specs: { capacity: '20000mAh', output: '50W', body: 'Aluminum', indicator: 'LED' } },
    { name: 'Samsung 20000mAh 45W Power Bank', category: 'mobile-accessories', brand: 'Samsung', price: 49.99, stock: 112, sku: 'CC-PWB-SAM-002', description: '45W Super Fast Charging 2.0, dual USB-C ports, pass-through charging. Ergonomic anti-slip design.', shortDesc: '20000mAh, 45W, dual USB-C, pass-through', tags: ['power-bank', 'samsung', '20000mah', '45w'], specs: { capacity: '20000mAh', output: '45W', ports: 'Dual USB-C', feature: 'Pass-through charging' } },
    { name: 'UGREEN USB-C to USB-C 100W 2m Cable', category: 'mobile-accessories', brand: 'UGREEN', price: 12.99, stock: 400, sku: 'CC-CBL-UGR-001', description: 'Braided nylon, 100W PD fast charging, 480Mbps data transfer, aluminum connectors. 10,000+ bend lifespan tested.', shortDesc: '2m braided, 100W PD, 480Mbps data', tags: ['cable', 'ugreen', 'usb-c', '100w'], specs: { length: '2m', power: '100W PD', data: '480Mbps', material: 'Braided nylon' } },
    { name: 'Anker 333 USB-C to Lightning 6ft', category: 'mobile-accessories', brand: 'Anker', price: 15.99, stock: 267, sku: 'CC-CBL-ANK-002', description: 'MFi-certified, Power Delivery fast charging, double-braided nylon for durability. 6-foot extended reach for convenience.', shortDesc: '6ft, MFi certified, PD fast charge, braided', tags: ['cable', 'anker', 'lightning', 'mfi'], specs: { length: '6ft', certification: 'MFi', connectors: 'USB-C to Lightning', material: 'Double-braided nylon' } },
    { name: 'Apple USB-C to Lightning Cable 1m', category: 'mobile-accessories', brand: 'Apple', price: 19.00, stock: 200, sku: 'CC-CBL-APL-003', description: 'Official Apple USB-C to Lightning cable. MFi certified, supports fast charging for iPhone 8 and newer. 1 meter length.', shortDesc: '1m, official Apple, MFi certified', tags: ['cable', 'apple', 'lightning', 'official'], specs: { length: '1m', connectors: 'USB-C to Lightning', certification: 'MFi' } },
    { name: 'Spigen Tough Armor iPhone 15 Pro Max', category: 'mobile-accessories', brand: 'Spigen', price: 16.99, stock: 300, sku: 'CC-MCV-SPG-001', description: 'Military-grade drop protection, Air Cushion Technology corners, built-in kickstand, MagSafe compatible. Dual-layer protection.', shortDesc: 'Military-grade, Air Cushion, MagSafe, kickstand', tags: ['case', 'spigen', 'iphone-15', 'rugged'], specs: { protection: 'Military-grade', tech: 'Air Cushion', compatibility: 'iPhone 15 Pro Max', feature: 'MagSafe + Kickstand' } },
    { name: 'Belkin UltraGlass 2 iPhone 15 Pro', category: 'mobile-accessories', brand: 'Belkin', price: 39.99, stock: 200, sku: 'CC-SPR-BEL-001', description: 'Double ion-exchange glass, antimicrobial coating, Easy Align tray for perfect application. 9H surface hardness.', shortDesc: '9H hardness, antimicrobial, Easy Align tray', tags: ['screen-protector', 'belkin', 'iphone-15', '9h'], specs: { hardness: '9H', material: 'Double ion-exchange glass', coating: 'Antimicrobial', application: 'Easy Align Tray' } },

    // ===== 4. AUDIO =====
    { name: 'Apple AirPods Pro (2nd Gen) USB-C', category: 'audio', brand: 'Apple', price: 249.99, stock: 120, sku: 'CC-WEB-APL-001', description: 'H2 chip, Adaptive Audio, Conversation Awareness, 30-hour total battery with MagSafe USB-C case. Industry-leading ANC.', shortDesc: 'H2 chip, Adaptive Audio, 30hr, USB-C', tags: ['earbuds', 'apple', 'airpods', 'anc'], specs: { chip: 'H2', anc: 'Adaptive ANC', battery: '30 hours total', charging: 'MagSafe USB-C' }, isFeatured: true },
    { name: 'Sony WF-1000XM5', category: 'audio', brand: 'Sony', price: 299.99, stock: 67, sku: 'CC-WEB-SNY-001', description: 'V2 processor, QN2e ANC chip, 8-hour battery (24hr with case), LDAC hi-res audio. 20% smaller and lighter than XM4.', shortDesc: 'V2 chip, QN2e ANC, LDAC, 8hr battery', tags: ['earbuds', 'sony', 'anc', 'hi-res'], specs: { processor: 'V2 + QN2e', anc: 'Active Noise Cancellation', battery: '8hr + 24hr case', audio: 'LDAC Hi-Res' } },
    { name: 'Samsung Galaxy Buds3 Pro', category: 'audio', brand: 'Samsung', price: 229.99, stock: 94, sku: 'CC-WEB-SAM-002', description: 'Blade design, adaptive ANC, 24-bit hi-fi sound, Galaxy AI real-time translation. IP57 water resistance.', shortDesc: 'Blade design, adaptive ANC, 24-bit hi-fi', tags: ['earbuds', 'samsung', 'anc', 'galaxy-ai'], specs: { design: 'Blade', anc: 'Adaptive ANC', audio: '24-bit Hi-Fi', ip: 'IP57' } },
    { name: 'Sony WH-1000XM5', category: 'audio', brand: 'Sony', price: 379.99, stock: 56, sku: 'CC-HDP-SNY-001', description: '8-microphone ANC system, Auto NC Optimizer, 30-hour battery, speak-to-chat, crystal clear hands-free calling.', shortDesc: '8-mic ANC, 30hr battery, speak-to-chat', tags: ['headphones', 'sony', 'anc', 'wireless'], specs: { anc: '8-mic system', battery: '30 hours', drivers: '30mm', weight: '250g' }, isFeatured: true, comparePrice: 399.99 },
    { name: 'Bose QuietComfort Ultra', category: 'audio', brand: 'Bose', price: 429.99, stock: 38, sku: 'CC-HDP-BOS-002', description: 'CustomTune personalized audio, Immersive Audio spatial sound, multipoint Bluetooth, premium comfort for all-day wear.', shortDesc: 'CustomTune, Immersive Audio, multipoint', tags: ['headphones', 'bose', 'anc', 'premium'], specs: { anc: 'CustomTune ANC', audio: 'Immersive Audio', connectivity: 'Multipoint Bluetooth', comfort: 'Premium cushion' } },
    { name: 'JBL Tour One M2', category: 'audio', brand: 'JBL', price: 249.99, stock: 43, sku: 'CC-HDP-JBL-001', description: 'True Adaptive ANC, Smart Ambient mode, JBL Pro Sound, Personi-Fi 2.0 personalized spatial audio. Foldable design.', shortDesc: 'Adaptive ANC, JBL Pro Sound, Personi-Fi 2.0', tags: ['headphones', 'jbl', 'anc', 'spatial-audio'], specs: { anc: 'True Adaptive ANC', audio: 'JBL Pro Sound + Personi-Fi 2.0', battery: '50 hours', design: 'Foldable' } },
    { name: 'JBL Charge 5', category: 'audio', brand: 'JBL', price: 179.99, stock: 78, sku: 'CC-BSP-JBL-001', description: 'IP67 waterproof and dustproof, 20-hour battery, built-in power bank for charging devices, PartyBoost for linking multiple speakers.', shortDesc: 'IP67, 20hr battery, built-in power bank', tags: ['speaker', 'jbl', 'bluetooth', 'waterproof'], specs: { battery: '20 hours', ip: 'IP67', feature: 'Built-in power bank', driver: 'Racetrack + dual bass' } },
    { name: 'Bose SoundLink Flex', category: 'audio', brand: 'Bose', price: 149.99, stock: 67, sku: 'CC-BSP-BOS-003', description: 'PositionIQ technology auto-adjusts sound, IP67 waterproof, custom transducer for deep bass. Compact, rugged, premium sound.', shortDesc: 'PositionIQ, IP67, custom transducer', tags: ['speaker', 'bose', 'bluetooth', 'portable'], specs: { technology: 'PositionIQ', ip: 'IP67', battery: '12 hours', driver: 'Custom transducer' } },
    { name: 'Sony SRS-XB100', category: 'audio', brand: 'Sony', price: 59.99, stock: 134, sku: 'CC-BSP-SNY-002', description: 'EXTRA BASS enhanced low end, 16-hour battery, IP67 waterproof, Sound Diffusion Processor. Multiway strap included for portability.', shortDesc: 'EXTRA BASS, 16hr, IP67, ultra-portable', tags: ['speaker', 'sony', 'bluetooth', 'portable'], specs: { sound: 'EXTRA BASS', battery: '16 hours', ip: 'IP67', feature: 'Multiway strap' } },

    // ===== 5. STORAGE =====
    { name: 'SanDisk Ultra Dual Drive Luxe 256GB', category: 'storage', brand: 'SanDisk', price: 29.99, stock: 200, sku: 'CC-USD-SND-001', description: 'USB-C + USB-A dual connector, 150MB/s read speed, all-metal swivel design. Auto-backup app for Android devices.', shortDesc: '256GB, USB-C + USB-A, 150MB/s, metal', tags: ['usb', 'sandisk', '256gb', 'dual'], specs: { capacity: '256GB', speed: '150MB/s', connectors: 'USB-C + USB-A', design: 'All-metal swivel' } },
    { name: 'Samsung BAR Plus 256GB USB', category: 'storage', brand: 'Samsung', price: 34.99, stock: 150, sku: 'CC-USD-SAM-005', description: 'All-metal body with keyring hole, 300MB/s read speed. Waterproof, shockproof, magnet-proof, X-ray-proof, and temperature-proof.', shortDesc: '256GB, 300MB/s, metal, 5-proof durable', tags: ['usb', 'samsung', '256gb', 'durable'], specs: { capacity: '256GB', speed: '300MB/s', design: 'Metal body', durability: '5-proof (water, shock, magnet, x-ray, temp)' } },
    { name: 'Samsung T9 Portable SSD 2TB', category: 'storage', brand: 'Samsung', price: 219.99, stock: 67, sku: 'CC-ESS-SAM-002', description: 'Up to 2,000 MB/s read/write, USB 3.2 Gen 2x2, drop resistant to 3 meters. PS5 and Xbox compatible. Dynamic thermal guard.', shortDesc: '2TB, 2,000 MB/s, USB 3.2 Gen 2x2', tags: ['ssd', 'samsung', 'portable', '2tb'], specs: { capacity: '2TB', speed: '2000 MB/s', interface: 'USB 3.2 Gen 2x2', durability: '3m drop resistant' } },
    { name: 'SanDisk Extreme Portable SSD V2 2TB', category: 'storage', brand: 'SanDisk', price: 179.99, stock: 89, sku: 'CC-ESS-SND-004', description: 'Up to 1,050MB/s read, IP55 water/dust resistance, shock resistant up to 2m. Password protection with 256-bit AES hardware encryption.', shortDesc: '2TB, 1,050MB/s, IP55, 256-bit AES', tags: ['ssd', 'sandisk', 'portable', 'rugged'], specs: { capacity: '2TB', speed: '1050 MB/s', ip: 'IP55', security: '256-bit AES' } },
    { name: 'WD My Passport SSD 2TB', category: 'storage', brand: 'WD', price: 159.99, stock: 112, sku: 'CC-ESS-WD-004', description: 'Up to 1,050MB/s reads, sleek metal design available in multiple colors. 256-bit AES hardware encryption for data security.', shortDesc: '2TB, 1,050MB/s, metal design, AES encryption', tags: ['ssd', 'wd', 'portable', 'encrypted'], specs: { capacity: '2TB', speed: '1050 MB/s', design: 'Metal, multi-color', security: '256-bit AES' } },
    { name: 'Synology DS923+ 4-Bay NAS', category: 'storage', brand: 'Synology', price: 599.99, stock: 23, sku: 'CC-NAS-SYN-001', description: 'AMD Ryzen R1600 processor, expandable to 32GB RAM + 9 drives with expansion unit. DSM OS with comprehensive app ecosystem. Optional 10GbE upgrade.', shortDesc: '4-bay, Ryzen R1600, expandable, DSM OS', tags: ['nas', 'synology', '4-bay', 'ryzen'], specs: { bays: '4 (+5 expansion)', processor: 'AMD Ryzen R1600', ram: '4GB (up to 32GB)', network: '1GbE (10GbE optional)' } },
    { name: 'QNAP TS-464 4-Bay NAS', category: 'storage', brand: 'QNAP', price: 499.99, stock: 34, sku: 'CC-NAS-QNP-001', description: 'Intel Celeron N5095 quad-core, 4GB RAM, HDMI 2.0 output, dual 2.5GbE ports. QTS 5.1 with AI-powered photo management.', shortDesc: '4-bay, Intel N5095, HDMI 2.0, 2.5GbE', tags: ['nas', 'qnap', '4-bay', 'intel'], specs: { bays: '4', processor: 'Intel Celeron N5095', ram: '4GB', network: '2x 2.5GbE', hdmi: 'HDMI 2.0' } },

    // ===== 6. NETWORKING =====
    { name: 'ASUS RT-AX86U Pro AX5700', category: 'networking', brand: 'ASUS', price: 249.99, stock: 45, sku: 'CC-WRT-ASU-001', description: 'Dual-band Wi-Fi 6 router with 2.5G WAN, dedicated gaming port, RangeBoost Plus, AiProtection Pro security, Adaptive QoS.', shortDesc: 'AX5700 Wi-Fi 6, 2.5G WAN, gaming optimized', tags: ['router', 'asus', 'wifi-6', 'gaming'], specs: { speed: 'AX5700', bands: 'Dual-band', wan: '2.5GbE', security: 'AiProtection Pro' } },
    { name: 'TP-Link Archer AXE75 AXE5400', category: 'networking', brand: 'TP-Link', price: 199.99, stock: 73, sku: 'CC-WRT-TPL-001', description: 'Tri-band Wi-Fi 6E with new 6GHz band, 1.7GHz quad-core processor, HomeShield security. OFDMA and MU-MIMO for efficient multi-device handling.', shortDesc: 'AXE5400 Wi-Fi 6E, tri-band, 6GHz', tags: ['router', 'tp-link', 'wifi-6e', 'tri-band'], specs: { speed: 'AXE5400', bands: 'Tri-band (incl. 6GHz)', processor: '1.7GHz quad-core', security: 'HomeShield' } },
    { name: 'Netgear Nighthawk XR1000', category: 'networking', brand: 'Netgear', price: 349.99, stock: 34, sku: 'CC-WRT-NET-001', description: 'DumaOS 3.0 gaming OS, geo-filtering for low-ping servers, ping heatmap, 1.5GHz triple-core processor. Purpose-built for competitive gaming.', shortDesc: 'DumaOS 3.0, geo-filtering, gaming router', tags: ['router', 'netgear', 'gaming', 'dumaos'], specs: { os: 'DumaOS 3.0', speed: 'AX5400', processor: '1.5GHz triple-core', feature: 'Geo-filtering' } },
    { name: 'Ubiquiti UniFi Dream Router', category: 'networking', brand: 'Ubiquiti', price: 199.99, stock: 34, sku: 'CC-MSH-UBI-001', description: 'All-in-one UniFi console with Wi-Fi 6 access point, 4x4 MU-MIMO, advanced traffic management. UniFi Network application pre-installed.', shortDesc: 'UniFi console, Wi-Fi 6, 4x4 MU-MIMO', tags: ['router', 'ubiquiti', 'unifi', 'wifi-6'], specs: { type: 'UniFi Console', wifi: 'Wi-Fi 6 AP', mimo: '4x4 MU-MIMO', management: 'UniFi Network' } },
    { name: 'ASUS ZenWiFi AX XT8 (2-pack)', category: 'networking', brand: 'ASUS', price: 299.99, stock: 45, sku: 'CC-MSH-ASU-006', description: 'Tri-band mesh Wi-Fi system, up to 5,500 sq ft whole-home coverage. AiProtection Pro network security. Elegant design blends into any home.', shortDesc: 'Tri-band mesh, 5,500 sq ft, 2-pack', tags: ['mesh', 'asus', 'zenwifi', 'tri-band'], specs: { type: 'Mesh System', coverage: '5,500 sq ft', bands: 'Tri-band AX6600', security: 'AiProtection Pro' } },

    // ===== 7. SECURITY & SURVEILLANCE =====
    { name: 'Hikvision DS-2CD2087G2-LU 4K ColorVu', category: 'security-surveillance', brand: 'Hikvision', price: 149.99, stock: 56, sku: 'CC-CCT-HIK-001', description: '4K ColorVu 24/7 full color imaging, AcuSense 2.0 human/vehicle detection, 130dB WDR, IP67 weatherproof, IK10 vandal-resistant, built-in microphone.', shortDesc: '4K ColorVu, AcuSense 2.0, IP67, IK10', tags: ['cctv', 'hikvision', '4k', 'colorvu'], specs: { resolution: '4K (8MP)', feature: 'ColorVu 24/7 Color', detection: 'AcuSense 2.0 Human/Vehicle', rating: 'IP67 + IK10' } },
    { name: 'Dahua IPC-HDW3849H-AS-PV 8MP', category: 'security-surveillance', brand: 'Dahua', price: 129.99, stock: 78, sku: 'CC-CCT-DAH-001', description: 'Active deterrence with built-in strobe light and siren, 8MP resolution, Smart IR up to 50m, AI false alarm filtering technology.', shortDesc: '8MP, active deterrence, AI false alarm filter', tags: ['cctv', 'dahua', '8mp', 'deterrence'], specs: { resolution: '8MP', feature: 'Light + Siren Deterrence', ir: 'Smart IR 50m', ai: 'False alarm filtering' } },
    { name: 'Reolink RLC-810A 4K PoE', category: 'security-surveillance', brand: 'Reolink', price: 89.99, stock: 120, sku: 'CC-CCT-REO-001', description: '4K resolution with person/vehicle detection, Power over Ethernet, IP66 weatherproof. Local microSD storage, no subscription fees required.', shortDesc: '4K PoE, person/vehicle detection, no fees', tags: ['cctv', 'reolink', '4k', 'poe'], specs: { resolution: '4K', type: 'PoE', detection: 'Person + Vehicle', storage: 'microSD (no subscription)' } },
    { name: 'Ring Video Doorbell Pro 2', category: 'security-surveillance', brand: 'Ring', price: 259.99, stock: 43, sku: 'CC-SDB-RNG-001', description: '1536p head-to-toe video, 3D Motion Detection with Bird\'s Eye View, Alexa Greetings. Hardwired premium doorbell experience.', shortDesc: '1536p HD+, 3D Motion, Bird\'s Eye View', tags: ['doorbell', 'ring', 'smart', 'video'], specs: { resolution: '1536p HD+', detection: '3D Motion + Bird\'s Eye View', power: 'Hardwired', integration: 'Alexa' } },
    { name: 'Google Nest Doorbell (Battery)', category: 'security-surveillance', brand: 'Google', price: 179.99, stock: 67, sku: 'CC-SDB-GOO-001', description: 'Wire-free battery-powered design, 24/7 live view with HDR, intelligent alerts for people, packages, animals, and vehicles.', shortDesc: 'Battery, HDR, intelligent alerts, wire-free', tags: ['doorbell', 'google', 'nest', 'wireless'], specs: { type: 'Battery/Wire-free', video: 'HDR', alerts: 'People, Package, Animal, Vehicle', feature: '24/7 Live View' } },

    // ===== 8. CAMERAS & PHOTOGRAPHY =====
    { name: 'Canon EOS 90D Body', category: 'cameras-photography', brand: 'Canon', price: 1199.99, stock: 15, sku: 'CC-DSL-CAN-001', description: '32.5MP APS-C sensor, 10fps continuous shooting, 4K 30p uncropped video, Dual Pixel CMOS AF, vari-angle touchscreen, weather-sealed body.', shortDesc: '32.5MP APS-C, 10fps, 4K, weather-sealed', tags: ['camera', 'canon', 'dslr', 'aps-c'], specs: { sensor: '32.5MP APS-C', burst: '10fps', video: '4K 30p', af: 'Dual Pixel CMOS AF' } },
    { name: 'Nikon D850 Body', category: 'cameras-photography', brand: 'Nikon', price: 2499.99, stock: 8, sku: 'CC-DSL-NIK-001', description: '45.7MP full-frame sensor, 7fps (9fps with grip), 153-point AF system, 4K UHD video. Exceptional dynamic range for professionals.', shortDesc: '45.7MP full-frame, 7fps, 153-point AF', tags: ['camera', 'nikon', 'dslr', 'full-frame'], specs: { sensor: '45.7MP Full-Frame', burst: '7-9fps', af: '153-point', video: '4K UHD' } },
    { name: 'Sony Alpha 7 IV', category: 'cameras-photography', brand: 'Sony', price: 2499.99, stock: 12, sku: 'CC-MIR-SNY-001', description: '33MP full-frame, Real-time Eye AF for humans/animals/birds, 4K 60p 10-bit 4:2:2 video, 5-axis IBIS 5.5 stops. Hybrid photo/video powerhouse.', shortDesc: '33MP full-frame, Real-time Eye AF, 4K 60p 10-bit', tags: ['camera', 'sony', 'mirrorless', 'full-frame'], specs: { sensor: '33MP Full-Frame', af: 'Real-time Eye AF', video: '4K 60p 10-bit 4:2:2', stabilization: '5-axis 5.5-stop IBIS' } },
    { name: 'Canon EOS R6 Mark II', category: 'cameras-photography', brand: 'Canon', price: 2499.99, stock: 18, sku: 'CC-MIR-CAN-003', description: '24.2MP, 40fps electronic shutter, Dual Pixel CMOS AF II, 4K 60p oversampled from 6K. Versatile full-frame mirrorless.', shortDesc: '24.2MP, 40fps, 6K oversampled 4K', tags: ['camera', 'canon', 'mirrorless', 'full-frame'], specs: { sensor: '24.2MP Full-Frame', burst: '40fps electronic', af: 'Dual Pixel CMOS AF II', video: '4K 60p (6K oversampled)' } },
    { name: 'Fujifilm X-T5', category: 'cameras-photography', brand: 'Fujifilm', price: 1699.99, stock: 28, sku: 'CC-MIR-FUJ-001', description: '40MP APS-C X-Trans 5 HR sensor, 7-stop IBIS, classic dial operation, film simulation modes. Beautiful retro design with modern capabilities.', shortDesc: '40MP X-Trans 5, 7-stop IBIS, film sims', tags: ['camera', 'fujifilm', 'mirrorless', 'aps-c'], specs: { sensor: '40MP X-Trans 5 HR', stabilization: '7-stop IBIS', design: 'Retro dials', feature: 'Film Simulations' } },
    { name: 'GoPro HERO12 Black', category: 'cameras-photography', brand: 'GoPro', price: 399.99, stock: 89, sku: 'CC-ACT-GOP-001', description: '5.3K60 video with HDR, HyperSmooth 6.0 stabilization, 177° FOV in 8:7 aspect ratio. 2x longer runtime than HERO11.', shortDesc: '5.3K60 HDR, HyperSmooth 6.0, 177° FOV', tags: ['camera', 'gopro', 'action', 'waterproof'], specs: { video: '5.3K60 HDR', stabilization: 'HyperSmooth 6.0', fov: '177° in 8:7', waterproof: '33ft / 10m' } },
    { name: 'DJI Osmo Action 4', category: 'cameras-photography', brand: 'DJI', price: 349.99, stock: 67, sku: 'CC-ACT-DJI-002', description: '1/1.3" large sensor, 4K/120fps slow motion, 10-bit D-Log M color, 18m waterproof without housing. Magnetic quick-release mounting system.', shortDesc: '1/1.3" sensor, 4K120, 18m waterproof', tags: ['camera', 'dji', 'action', 'waterproof'], specs: { sensor: '1/1.3"', video: '4K/120fps', color: '10-bit D-Log M', waterproof: '18m (no housing)' } },

    // ===== 9. GAMING =====
    { name: 'Secretlab TITAN Evo 2022', category: 'gaming', brand: 'Secretlab', price: 549.99, stock: 23, sku: 'CC-GCH-SEC-001', description: 'Cold-cure foam technology, 4-way L-ADAPT lumbar support, magnetic memory foam head pillow, CloudSwap 4D armrests. 5-year warranty.', shortDesc: 'Cold-cure foam, 4-way lumbar, 5-year warranty', tags: ['chair', 'secretlab', 'gaming', 'ergonomic'], specs: { foam: 'Cold-cure', lumbar: '4-way L-ADAPT', armrests: 'CloudSwap 4D', warranty: '5 years' } },
    { name: 'Herman Miller x Logitech G Embody', category: 'gaming', brand: 'Herman Miller', price: 1795.00, stock: 8, sku: 'CC-GCH-HER-001', description: 'BackFit adjustment for spinal alignment, pixelated support for micro-movements, copper-infused cooling foam. 12-year warranty. The ultimate gaming chair.', shortDesc: 'BackFit, copper cooling foam, 12-year warranty', tags: ['chair', 'herman-miller', 'gaming', 'premium'], specs: { back: 'BackFit adjustment', seat: 'Pixelated support', foam: 'Copper-infused cooling', warranty: '12 years' } },
    { name: 'Xbox Wireless Controller (Robot White)', category: 'gaming', brand: 'Microsoft', price: 59.99, stock: 200, sku: 'CC-CTL-MIC-001', description: 'Refined ergonomics with textured grips, Bluetooth + Xbox Wireless connectivity, custom button mapping via Xbox Accessories app, dedicated Share button.', shortDesc: 'Wireless, textured grip, Share button', tags: ['controller', 'xbox', 'wireless', 'gaming'], specs: { connectivity: 'Bluetooth + Xbox Wireless', compatibility: 'Xbox Series X|S, PC, Mobile', features: 'Share button, custom mapping' } },
    { name: 'PlayStation DualSense Edge', category: 'gaming', brand: 'Sony', price: 199.99, stock: 89, sku: 'CC-CTL-SNY-006', description: 'Replaceable stick modules, back buttons, adjustable trigger stops, customizable sensitivity curves, Fn quick-access buttons. Pro-grade PS5 controller.', shortDesc: 'Replaceable sticks, back buttons, trigger stops', tags: ['controller', 'ps5', 'dualsense', 'pro'], specs: { platform: 'PS5/PC', features: 'Replaceable sticks, back buttons, trigger stops, Fn keys', type: 'Wireless' } },
    { name: 'Logitech G923 Racing Wheel', category: 'gaming', brand: 'Logitech', price: 399.99, stock: 28, sku: 'CC-RWH-LOG-006', description: 'TRUEFORCE force feedback technology, dual-clutch launch control, hand-stitched leather wheel, steel pedals with progressive brake. Xbox/PC compatible.', shortDesc: 'TRUEFORCE, dual-clutch launch, leather wheel', tags: ['racing-wheel', 'logitech', 'force-feedback'], specs: { feedback: 'TRUEFORCE', wheel: 'Leather wrapped', pedals: 'Steel with progressive brake', compatibility: 'Xbox + PC' } },
    { name: 'Elgato HD60 X Capture Card', category: 'gaming', brand: 'Elgato', price: 199.99, stock: 56, sku: 'CC-CCP-ELG-003', description: '1080p60 capture with HDR10 passthrough, VRR passthrough up to 1440p120/4K60. Low-latency for OBS, Streamlabs, and Twitch Studio.', shortDesc: '1080p60 capture, HDR10+VRR passthrough', tags: ['capture-card', 'elgato', 'streaming'], specs: { capture: '1080p60', passthrough: '4K60 HDR10 + VRR', interface: 'USB 3.0', software: 'OBS, Streamlabs, Twitch Studio' } },

    // ===== 10. SMART HOME =====
    { name: 'Philips Hue White and Color Ambiance Starter Kit', category: 'smart-home', brand: 'Philips', price: 199.99, stock: 67, sku: 'CC-SBL-PHI-001', description: '4 smart bulbs + Hue Bridge, 16 million colors and shades of white, voice control via Alexa/Google/HomeKit, Hue Sync for immersive entertainment.', shortDesc: '4 bulbs + Bridge, 16M colors, voice control', tags: ['smart-bulb', 'philips', 'hue', 'color'], specs: { bulbs: '4x A19 E26', colors: '16 million', hub: 'Hue Bridge included', control: 'App + Voice (Alexa/Google/HomeKit)' } },
    { name: 'TP-Link Kasa KL135 Smart Bulb (4-pack)', category: 'smart-home', brand: 'TP-Link', price: 39.99, stock: 200, sku: 'CC-SBL-TPL-007', description: 'Multicolor smart bulbs, 850 lumens brightness, Kasa app scheduling and scenes, Alexa/Google voice control. No hub required, works directly with Wi-Fi.', shortDesc: '4-pack, multicolor, 850lm, no hub needed', tags: ['smart-bulb', 'tp-link', 'kasa', 'wifi'], specs: { bulbs: '4x A19', lumens: '850', connectivity: 'Wi-Fi (no hub)', control: 'App + Voice' } },
    { name: 'TP-Link Kasa EP25 Smart Plug Mini (4-pack)', category: 'smart-home', brand: 'TP-Link', price: 29.99, stock: 300, sku: 'CC-SPL-TPL-008', description: 'Compact design leaves adjacent outlets free, voice control with Alexa/Google, scheduling and timer functions, energy monitoring. No hub required.', shortDesc: '4-pack, compact, energy monitoring, Wi-Fi', tags: ['smart-plug', 'tp-link', 'kasa', 'energy'], specs: { plugs: '4x Mini', features: 'Scheduling, Timer, Energy Monitor', control: 'App + Voice', connectivity: 'Wi-Fi (no hub)' } },
    { name: 'Philips Hue Smart Dimmer Switch', category: 'smart-home', brand: 'Philips', price: 24.99, stock: 150, sku: 'CC-SSW-PHI-002', description: 'Mountable or portable remote, controls up to 10 Hue smart lights simultaneously, battery-powered with 3-year life, easy peel-and-stick installation.', shortDesc: 'Controls 10 lights, portable, 3yr battery', tags: ['smart-switch', 'philips', 'hue', 'dimmer'], specs: { control: 'Up to 10 Hue lights', mounting: 'Wall or portable', battery: '3-year life', installation: 'Peel-and-stick' } },

    // ===== 11. LAPTOP ACCESSORIES =====
    { name: 'Peak Design Everyday Backpack V2 30L', category: 'laptop-accessories', brand: 'Peak Design', price: 289.99, stock: 34, sku: 'CC-LPB-PD-001', description: 'FlexFold dividers for customizable organization, weatherproof 400D recycled nylon, MagLatch closure system, dedicated 16" laptop sleeve. Lifetime warranty.', shortDesc: '30L, weatherproof, 16" laptop, FlexFold', tags: ['backpack', 'peak-design', 'laptop', 'premium'], specs: { capacity: '30L', material: '400D weatherproof nylon', laptop: 'Up to 16"', dividers: 'FlexFold' } },
    { name: 'Rain Design mStand Laptop Stand', category: 'laptop-accessories', brand: 'Rain Design', price: 49.99, stock: 120, sku: 'CC-LPS-RND-001', description: 'Single piece aluminum construction, cable organizer in back, raises screen to ergonomic eye level. Compatible with all laptops. Improves airflow and posture.', shortDesc: 'Aluminum, ergonomic, cable organizer', tags: ['stand', 'rain-design', 'aluminum', 'ergonomic'], specs: { material: 'Single-piece aluminum', compatibility: 'All laptops', feature: 'Cable organizer, eye-level height' } },
    { name: 'Anker 575 USB-C Docking Station 13-in-1', category: 'laptop-accessories', brand: 'Anker', price: 249.99, stock: 45, sku: 'CC-LPD-ANK-008', description: '13-in-1 USB-C hub with dual 4K HDMI display outputs, 100W Power Delivery pass-through, USB-C and USB-A data ports, Gigabit Ethernet, SD and microSD card slots.', shortDesc: '13-in-1, dual 4K HDMI, 100W PD', tags: ['dock', 'anker', 'usb-c', '13-in-1'], specs: { ports: '13 total', display: 'Dual 4K HDMI', charging: '100W PD pass-through', network: 'Gigabit Ethernet' } },

    // ===== 12. OFFICE ELECTRONICS =====
    { name: 'Brother HL-L2350DW Monochrome Laser Printer', category: 'office-electronics', brand: 'Brother', price: 149.99, stock: 56, sku: 'CC-PRI-BRO-001', description: '32 pages per minute, automatic duplex (2-sided) printing, 250-sheet paper capacity, Wi-Fi Direct + mobile printing. TN-730 toner yields 1,200 pages.', shortDesc: '32ppm, duplex, Wi-Fi, 250-sheet tray', tags: ['printer', 'brother', 'laser', 'monochrome'], specs: { speed: '32ppm', duplex: 'Automatic', capacity: '250 sheets', connectivity: 'Wi-Fi Direct' } },
    { name: 'Epson EcoTank ET-3850', category: 'office-electronics', brand: 'Epson', price: 399.99, stock: 34, sku: 'CC-PRI-EPS-001', description: 'Cartridge-free supertank printer, includes up to 2 years of ink in the box, auto duplex printing, automatic document feeder, wireless connectivity.', shortDesc: 'Cartridge-free, 2 years ink included, ADF', tags: ['printer', 'epson', 'ecotank', 'all-in-one'], specs: { type: 'Cartridge-free Supertank', ink: 'Up to 2 years included', features: 'Auto duplex, ADF, wireless' } },
    { name: 'BenQ TK700STi 4K Projector', category: 'office-electronics', brand: 'BenQ', price: 1499.99, stock: 12, sku: 'CC-PRJ-BEN-001', description: 'True 4K UHD resolution, 3000 ANSI lumens brightness, 4ms input lag at 1080p/240Hz, Android TV built-in. Short throw: 100" screen from just 6.5 feet.', shortDesc: '4K HDR, 3000 lumens, 4ms, Android TV', tags: ['projector', 'benq', '4k', 'gaming'], specs: { resolution: '4K UHD', brightness: '3000 lumens', 'input lag': '4ms @ 1080p/240Hz', throw: 'Short throw (100" @ 6.5ft)' } },

    // ===== 13. CABLES & ADAPTERS =====
    { name: 'UGREEN HDMI 2.1 Cable 8K 6ft', category: 'cables-adapters', brand: 'UGREEN', price: 14.99, stock: 300, sku: 'CC-HDM-UGR-001', description: 'Certified Ultra High Speed HDMI 2.1 cable. Supports 8K@60Hz and 4K@120Hz, 48Gbps bandwidth, eARC, Dolby Vision/HDR10+. Braided nylon construction.', shortDesc: '8K@60Hz, 48Gbps, certified HDMI 2.1', tags: ['cable', 'ugreen', 'hdmi', '8k'], specs: { version: 'HDMI 2.1', bandwidth: '48Gbps', resolution: '8K@60Hz / 4K@120Hz', material: 'Braided nylon' } },
    { name: 'Anker PowerExpand 6-in-1 USB-C Hub', category: 'cables-adapters', brand: 'Anker', price: 49.99, stock: 150, sku: 'CC-USB-ANK-009', description: '6-in-1 USB-C hub with 4K HDMI output, 100W Power Delivery passthrough, USB-C data port, 2x USB-A 3.0 ports, SD and microSD card readers. Compact aluminum.', shortDesc: '6-in-1, 4K HDMI, 100W PD, SD reader', tags: ['hub', 'anker', 'usb-c', 'adapter'], specs: { ports: '6', hdmi: '4K@30Hz', charging: '100W PD', design: 'Compact aluminum' } },
    { name: 'Apple USB-C Digital AV Multiport Adapter', category: 'cables-adapters', brand: 'Apple', price: 69.00, stock: 120, sku: 'CC-USB-APL-004', description: 'Official Apple multiport adapter with USB-C pass-through charging, USB-A port, HDMI output up to 4K at 60Hz. Works with MacBook, iPad Pro, and more.', shortDesc: 'Official Apple, HDMI 4K60, USB-C + USB-A', tags: ['adapter', 'apple', 'usb-c', 'hdmi'], specs: { ports: 'USB-C (charging) + USB-A + HDMI', hdmi: '4K@60Hz', brand: 'Apple Official' } },

    // ===== 14. POWER SOLUTIONS =====
    { name: 'APC Back-UPS Pro BR1500G', category: 'power-solutions', brand: 'APC', price: 219.99, stock: 34, sku: 'CC-UPS-APC-001', description: '1500VA/865W capacity, 10 outlets (5 battery backup + 5 surge only), LCD status display, Automatic Voltage Regulation, PowerChute management software.', shortDesc: '1500VA/865W, 10 outlets, AVR, LCD', tags: ['ups', 'apc', 'battery-backup', '1500va'], specs: { capacity: '1500VA / 865W', outlets: '10 (5 battery + 5 surge)', avr: 'Automatic Voltage Regulation', display: 'LCD' } },
    { name: 'Tripp Lite TLP1208TELTV Surge Protector', category: 'power-solutions', brand: 'Tripp Lite', price: 39.99, stock: 200, sku: 'CC-SUR-TRP-001', description: '12 outlets, 8-foot power cord, 4,320 joules of surge protection, telephone/modem/coax line protection. Lifetime warranty with $150,000 connected equipment insurance.', shortDesc: '12 outlets, 4,320J, lifetime warranty', tags: ['surge-protector', 'tripp-lite', '12-outlet'], specs: { outlets: '12', joules: '4320', cord: '8 ft', warranty: 'Lifetime + $150K insurance' } },
    { name: 'Anker 727 Charging Station 100W', category: 'power-solutions', brand: 'Anker', price: 59.99, stock: 89, sku: 'CC-EXT-ANK-010', description: 'Compact cube design with 2 AC outlets, 2 USB-C ports, 2 USB-A ports. 100W total power output. Perfect desktop and travel charging hub.', shortDesc: '2AC + 2C + 2A, 100W total, compact cube', tags: ['charger', 'anker', 'power-strip', '100w'], specs: { outlets: '2 AC', usb: '2x USB-C + 2x USB-A', power: '100W total', design: 'Compact cube' } },

    // ===== 15. WEARABLES =====
    { name: 'Apple Watch Series 9 45mm', category: 'wearables', brand: 'Apple', price: 429.99, stock: 112, sku: 'CC-SWT-APL-001', description: 'S9 SiP chip, Double Tap gesture control, 2000 nits always-on Retina display, on-device Siri, blood oxygen sensor, ECG, Crash Detection. Carbon neutral option.', shortDesc: 'S9 chip, Double Tap, 2000 nits, ECG', tags: ['smartwatch', 'apple', 'series-9', '45mm'], specs: { chip: 'S9 SiP', display: '2000 nits Always-On', health: 'ECG + Blood Oxygen + Temperature', feature: 'Double Tap + Crash Detection' } },
    { name: 'Samsung Galaxy Watch6 Classic 47mm', category: 'wearables', brand: 'Samsung', price: 399.99, stock: 78, sku: 'CC-SWT-SAM-003', description: 'Iconic rotating bezel, Wear OS 4, body composition analysis, advanced sleep coaching, Irregular Heart Rhythm Notification. Sapphire crystal display.', shortDesc: 'Rotating bezel, Wear OS 4, body composition', tags: ['smartwatch', 'samsung', 'galaxy-watch', 'wear-os'], specs: { size: '47mm', os: 'Wear OS 4', display: 'Sapphire crystal', health: 'Body composition + Sleep coaching' } },
    { name: 'Garmin fenix 7 Pro Solar', category: 'wearables', brand: 'Garmin', price: 799.99, stock: 34, sku: 'CC-SWT-GAR-001', description: 'Solar charging lens extends battery up to 37 days, multi-band GPS with SatIQ, sapphire lens, built-in maps, music storage, advanced training metrics.', shortDesc: 'Solar 37-day, multi-band GPS, sapphire', tags: ['smartwatch', 'garmin', 'fenix', 'solar'], specs: { battery: 'Up to 37 days solar', gps: 'Multi-band + SatIQ', lens: 'Sapphire', features: 'Maps, Music, Training metrics' } },
    { name: 'Meta Quest 3 512GB', category: 'wearables', brand: 'Meta', price: 649.99, stock: 45, sku: 'CC-VRH-MET-001', description: '4K+ Infinite Display, Snapdragon XR2 Gen 2 processor, pancake lenses (40% slimmer profile), full-color passthrough mixed reality. 512GB storage.', shortDesc: '4K+ display, XR2 Gen 2, pancake lenses, MR', tags: ['vr', 'meta', 'quest-3', 'mixed-reality'], specs: { display: '4K+ Infinite', processor: 'Snapdragon XR2 Gen 2', storage: '512GB', lenses: 'Pancake (40% slimmer)' } },
    { name: 'PlayStation VR2', category: 'wearables', brand: 'Sony', price: 549.99, stock: 67, sku: 'CC-VRH-SNY-007', description: '4K HDR OLED panels, 110° field of view, eye tracking with foveated rendering, haptic feedback in headset and Sense controllers, 3D audio. PS5 exclusive.', shortDesc: '4K HDR OLED, 110° FOV, eye tracking', tags: ['vr', 'sony', 'psvr2', 'ps5'], specs: { display: '4K HDR OLED', fov: '110°', tracking: 'Eye tracking', haptics: 'Headset + Controllers' } },

    // ===== 16. SOFTWARE & DIGITAL =====
    { name: 'Windows 11 Pro Retail License', category: 'software-digital', brand: 'Microsoft', price: 199.99, stock: 500, sku: 'CC-SFW-MIC-001', description: 'Genuine retail license key, transferable between PCs. Includes BitLocker encryption, Remote Desktop, Hyper-V virtualization, Windows Sandbox. Lifetime activation.', shortDesc: 'Genuine retail, transferable, lifetime', tags: ['software', 'windows', 'license', 'pro'], specs: { type: 'Retail License', features: 'BitLocker, Remote Desktop, Hyper-V, Sandbox', activation: 'Lifetime' }, isDigital: true },
    { name: 'Microsoft 365 Personal (1-Year)', category: 'software-digital', brand: 'Microsoft', price: 69.99, stock: 500, sku: 'CC-SFW-MIC-002', description: '1-year subscription for 1 user across 5 devices. Includes Word, Excel, PowerPoint, Outlook, 1TB OneDrive cloud storage, and premium creative content.', shortDesc: '1yr, 1 user, 5 devices, 1TB OneDrive', tags: ['software', 'microsoft-365', 'subscription', 'office'], specs: { duration: '1 Year', users: '1 user / 5 devices', apps: 'Word, Excel, PowerPoint, Outlook', storage: '1TB OneDrive' }, isDigital: true },
    { name: 'Norton 360 Deluxe (1-Year, 5 Devices)', category: 'software-digital', brand: 'Norton', price: 49.99, stock: 500, sku: 'CC-SFW-NOR-001', description: 'Comprehensive protection for 5 devices. Includes VPN, dark web monitoring, 50GB cloud backup, parental controls, and real-time threat protection.', shortDesc: '1yr, 5 devices, VPN, dark web monitor', tags: ['software', 'norton', 'antivirus', 'security'], specs: { devices: '5', vpn: 'Included', backup: '50GB cloud', feature: 'Dark web monitoring + Parental controls' }, isDigital: true },

    // ===== 17. DIY ELECTRONICS =====
    { name: 'Arduino Uno R4 WiFi', category: 'diy-electronics', brand: 'Arduino', price: 27.99, stock: 89, sku: 'CC-ARD-ARD-001', description: 'ARM Cortex-M4 32-bit microcontroller with built-in Wi-Fi and Bluetooth, 12x8 LED matrix display, Arduino Cloud integration. Compatible with most Uno R3 shields.', shortDesc: 'ARM Cortex-M4, Wi-Fi/BT, LED matrix', tags: ['arduino', 'uno', 'wifi', 'microcontroller'], specs: { processor: 'ARM Cortex-M4', connectivity: 'Wi-Fi + Bluetooth', display: '12x8 LED matrix', compatibility: 'Uno R3 shields' } },
    { name: 'Raspberry Pi 5 8GB', category: 'diy-electronics', brand: 'Raspberry Pi', price: 79.99, stock: 34, sku: 'CC-RBP-RBP-001', description: '2.4GHz quad-core Cortex-A76 processor, 8GB LPDDR4X RAM, dual 4Kp60 HDMI output, PCIe 2.0 interface, dual-band Wi-Fi, Bluetooth 5.0. 2-3x faster than Pi 4.', shortDesc: 'Cortex-A76, 8GB RAM, dual 4K HDMI', tags: ['raspberry-pi', 'pi-5', '8gb', 'sbc'], specs: { processor: '2.4GHz quad-core Cortex-A76', ram: '8GB LPDDR4X', display: 'Dual 4Kp60 HDMI', interface: 'PCIe 2.0' } },
    { name: 'Raspberry Pi 4 Model B 4GB', category: 'diy-electronics', brand: 'Raspberry Pi', price: 55.00, stock: 120, sku: 'CC-RBP-RBP-002', description: '1.5GHz quad-core processor, 4GB RAM, dual micro HDMI supporting 4K video, 2x USB 3.0, Gigabit Ethernet. The versatile classic single-board computer.', shortDesc: 'Quad-core, 4GB RAM, 4K, USB 3.0, GigE', tags: ['raspberry-pi', 'pi-4', '4gb', 'sbc'], specs: { processor: '1.5GHz quad-core', ram: '4GB', usb: '2x USB 3.0', network: 'Gigabit Ethernet' } },
    { name: 'ELEGOO UNO R3 Starter Kit', category: 'diy-electronics', brand: 'ELEGOO', price: 39.99, stock: 150, sku: 'CC-DIY-ELE-001', description: '200+ components including sensors, motors, LCD display, RFID module. Complete learning kit for Arduino beginners with detailed tutorials and projects.', shortDesc: '200+ components, tutorials, sensors, LCD', tags: ['kit', 'elegoo', 'arduino', 'starter'], specs: { components: '200+', inclusions: 'Sensors, motors, LCD, RFID', skill: 'Beginner', tutorials: 'Included' } },
    { name: 'Raspberry Pi High Quality Camera', category: 'diy-electronics', brand: 'Raspberry Pi', price: 49.99, stock: 78, sku: 'CC-DIY-RBP-003', description: '12.3MP Sony IMX477 sensor, C/CS-mount lens compatibility, tripod mount, back-illuminated sensor. For professional-quality Pi photography projects.', shortDesc: '12.3MP Sony IMX477, C/CS lens mount', tags: ['camera', 'raspberry-pi', 'hq-camera'], specs: { sensor: '12.3MP Sony IMX477', mount: 'C/CS lens', feature: 'Tripod mount', compatibility: 'All Raspberry Pi' } },

    // ===== 18. TOOLS & MAINTENANCE =====
    { name: 'iFixit Manta Driver Kit 112 Bit', category: 'tools-maintenance', brand: 'iFixit', price: 59.99, stock: 67, sku: 'CC-TLK-IFI-001', description: '112 precision steel bits for every electronic repair. Ergonomic aluminum handle with magnetic bit socket. Includes pentalobe, tri-wing, security torx, and game console bits. Lifetime warranty.', shortDesc: '112 bits, aluminum handle, lifetime warranty', tags: ['toolkit', 'ifixit', 'repair', 'manta'], specs: { bits: '112 precision steel', handle: 'Ergonomic aluminum', compatibility: 'All electronics + consoles', warranty: 'Lifetime' } },
    { name: 'ORIA Precision Screwdriver Set 86-in-1', category: 'tools-maintenance', brand: 'ORIA', price: 19.99, stock: 200, sku: 'CC-TLK-ORI-001', description: '56 precision bits with flexible shaft, extension rod, suction cup, spudgers, and tweezers. Magnetic driver with non-slip grip. Great value all-in-one kit.', shortDesc: '86-in-1, 56 bits, magnetic driver', tags: ['toolkit', 'oria', 'screwdriver', '86-in-1'], specs: { pieces: '86-in-1', bits: '56 precision', handle: 'Magnetic + non-slip grip', extras: 'Flex shaft, spudgers, tweezers, suction cup' } },
    { name: 'iFixit Essential Electronics Toolkit', category: 'tools-maintenance', brand: 'iFixit', price: 24.99, stock: 150, sku: 'CC-TLK-IFI-002', description: '16 precision bits, opening tools, spudgers, tweezers, suction handle. Compact and portable. Perfect starter kit for phone and laptop repairs.', shortDesc: '16 bits, opening tools, compact', tags: ['toolkit', 'ifixit', 'essential', 'portable'], specs: { bits: '16 precision', tools: 'Opening picks, spudgers, tweezers, suction cup', size: 'Portable', use: 'Phone + Laptop repair' } },
  ];

  for (const p of products) {
    const existing = await prisma.product.findUnique({ where: { sku: p.sku } });
    if (!existing) {
      const cat = getCat(p.category);
      const brand = getBrand(p.brand);
      const created = await prisma.product.create({
        data: {
          name: p.name,
          slug: s(p.name),
          sku: p.sku,
          description: p.description,
          shortDescription: p.shortDesc,
          price: p.price,
          comparePrice: p.comparePrice || null,
          stockQty: p.stock,
          isFeatured: p.isFeatured || false,
          isDigital: p.isDigital || false,
          tags: p.tags,
          specs: p.specs,
          categoryId: cat.id,
          brandId: brand?.id || null,
          images: {
            create: {
              url: `https://placehold.co/600x600/0F172A/3B82F6?text=${encodeURIComponent(p.name.substring(0, 30))}`,
              altText: p.name,
              isPrimary: true,
              sortOrder: 0,
            },
          },
        },
      });
    }
  }

  console.log(`Seeded ${products.length} products across 18 categories`);

  await prisma.coupon.upsert({
    where: { code: 'WELCOME20' },
    update: {},
    create: {
      code: 'WELCOME20',
      description: '20% off your first order',
      discountType: 'PERCENTAGE',
      discountValue: 20,
      minOrderAmount: 50,
      maxDiscount: 50,
      usageLimit: 100,
      startsAt: new Date(),
      expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      applicableCategories: [],
    },
  });

  console.log('\nSeed complete!');
  console.log('Demo Accounts:');
  console.log('  admin@coreconnect.com (admin123) | manager@coreconnect.com (manager123)');
  console.log('  employee1@coreconnect.com (employee123) | employee2@coreconnect.com (employee123)');
  console.log('  anne@coreconnect.com (anne123) | becker@coreconnect.com (becker123) | christine@coreconnect.com (christine123)');
  console.log('  jennifer@coreconnect.com (jennifer123) | david@coreconnect.com (david123) | emily@coreconnect.com (emily123)');
  console.log('  michael@coreconnect.com (michael123) | sophia@coreconnect.com (sophia123) | james@coreconnect.com (james123)');
  console.log('  olivia@coreconnect.com (olivia123) | daniel@coreconnect.com (daniel123) | grace@coreconnect.com (grace123)');
  console.log('  henry@coreconnect.com (henry123) | isabella@coreconnect.com (isabella123) | lucas@coreconnect.com (lucas123)');
  console.log('  victoria@coreconnect.com (victoria123) | ethan@coreconnect.com (ethan123) | ava@coreconnect.com (ava123)');
  console.log('  noah@coreconnect.com (noah123) | mia@coreconnect.com (mia123) | jack@coreconnect.com (jack123)');
  console.log('  lily@coreconnect.com (lily123) | oliver@coreconnect.com (oliver123)');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
